# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "APPNAME"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

session: "YAML"

engines:
  session:
    YAML:
      session_dir: "/tmp/dancer-sessions"

plugins:
  DBIC:
    default:
      dsn: dbi:mysql:database=scap;mysql_enable_utf8=1;host=localhost
      schema_class: APPNAME::Schema
      user: username
      pass: pass
      options:
        RaiseError: 1
        PrintError: 1

